#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

cd iceFoam
wmake
cd ../subModels/surfaceFilmModelsSWIM
wmake

# ----------------------------------------------------------------- end-of-file
