#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

cd subModels/surfaceFilmModelsSWIM
wmake
cd ../../subModels/particlesLib
wmake
cd ../../iceFoam
wmake
cd iceDyMFoam
wmake
# ----------------------------------------------------------------- end-of-file
