#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions    # Tutorial run functions

rm log.*

cd constant
rm -r polyMesh
cd wallFilmRegion
rm -r polyMesh
cd ../..

runApplication blockMesh
runApplication transformPoints -scale "(1 0 1)"
runApplication extrudeMesh

runApplication topoSet
runApplication extrudeToRegionMesh -overwrite

#------------------------------------------------------------------------------
